name: app

type: php:8.2.0

dependencies:
    php:
        - mbstring

web:
    locations:
        "/":
            root: "public"
            index:
                - index.php
            passthru: "/index.php"

disk: 512